# E:\intern_deploy\docker-compose.yml
version: "3.8"

services:
  backend:
    build: ./intern_backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres.lxjywvztsesakqfvnrho:nandini>samarth@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - NEXT_PUBLIC_KEYCLOAK_URL=http://keycloak:8080
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
      # - keycloak
    networks:
      - intern-network

  frontend:
    build:
      context: ./intern
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://103.192.198.177:4000/api
        NEXT_PUBLIC_KEYCLOAK_URL: https://103.192.198.177:8080
        NEXT_PUBLIC_RABBITMQ_URL: amqp://rabbitmq
    ports:
      - "3000:3000"
    depends_on:
      - backend
      # - keycloak
      - rabbitmq
    networks:
      - intern-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - intern-network

  # keycloak:
  #   image: quay.io/keycloak/keycloak:21.1.1
  #   environment:
  #     KEYCLOAK_ADMIN: admin
  #     KEYCLOAK_ADMIN_PASSWORD: admin
  #     KC_PROXY: edge
  #     KC_HOSTNAME_STRICT: "false"
  #     KC_HOSTNAME_STRICT_HTTPS: "false"
  #     KEYCLOAK_FRONTEND_URL: https://samarthprojectsk.duckdns.org/auth/
  #   command: start-dev --hostname-path=/auth
  #   ports:
  #     - "8080:8080"

networks:
  intern-network:
    driver: bridge
