version: "3.8"

services:
  backend:
    build: ./intern_backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres.lxjywvztsesakqfvnrho:nandini>samarth@aws-0-ap-south-1.pooler.supabase.com:5432/postgres
      - NEXT_PUBLIC_KEYCLOAK_URL=https://key-test.neev.work:8443
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - rabbitmq
      - keycloak
    networks:
      - intern-network

  frontend:
    build:
      context: ./intern
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://103.192.198.177:4000/api
        NEXT_PUBLIC_KEYCLOAK_URL: https://key-test.neev.work:8443
        NEXT_PUBLIC_RABBITMQ_URL: amqp://rabbitmq:5672
    ports:
      - "3001:3000" # HTTP for internal/testing
    depends_on:
      - backend
      - keycloak
      - rabbitmq
    networks:
      - intern-network

  nginx:
    image: nginx:alpine
    ports:
      - "3000:443" # HTTPS for frontend
    volumes:
      - /root/frontend/certs/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /root/frontend/certs/privkey.pem:/etc/nginx/certs/privkey.pem
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - intern-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - intern-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=key-test.neev.work
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=sam123
      - KC_PROXY=edge
      - KC_HTTPS_PORT=8443
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=true
    ports:
      - "8080:8080" # Optional HTTP for local testing
      - "8443:8443" # HTTPS for Keycloak
    volumes:
      - /root/keycloak/certs/fullchain.pem:/etc/x509/https/fullchain.pem
      - /root/keycloak/certs/privkey.pem:/etc/x509/https/privkey.pem
      - keycloak-data:/opt/keycloak/data
      - /root/keycloak/providers:/opt/keycloak/providers
      - /root/keycloak/themes:/opt/keycloak/themes
    entrypoint: >
      /bin/bash -c "
      /opt/keycloak/bin/kc.sh build &&
      /opt/keycloak/bin/kc.sh start --https-certificate-file=/etc/x509/https/fullchain.pem --https-certificate-key-file=/etc/x509/https/privkey.pem --hostname key-test.neev.work --optimized"
    networks:
      - intern-network
    healthcheck:
      test: ["CMD", "curl", "-f", "https://key-test.neev.work:8443"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: sam123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intern-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak", "-d", "keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  intern-network:
    driver: bridge

volumes:
  keycloak-data:
  postgres_data:
